# Site settings
title: Sercan Çelenk
email: sercancelenk@gmail.com
url: https://sercancelenk.github.io
description: "expert software engineer, sercan çelenk, developer, reactive programming, apache kafka, java, ruby, python, software development, agile, scrum"
keywords: "expert software engineer, sercan çelenk, developer, reactive programming, apache kafka, java, ruby, python, software development, agile, scrum"
skills: "Expert Software Engineer"
meta_author: Sercqn Çelenk

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: sercan

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Sercan Çelenk
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/thinkbyzas
  # - title: facebook
  #   url:
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/sercancelenk

# Postal address (add as many lines as necessary)
address:
  - line: Turkcell Technology
  - line: Izmir/Turkey

# Credits content
credits: 'Perspective of developer'

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag